### ISSUE TITLE
[PI] [BUG] Parasite Eve 2 French Version freezing **FIXED!!**

### ISSUE THREAD

**Issue by nemo93** [libretro/pcsx_rearmed#41]
Both the Euro (UK) and US versions do work! I mean that at least I could pass the very first screen and access the shooting range tutorial. With the FR version I just can't go beyond this "introduction" screen right after selecting New Game on the main title screen. It just sits there forever... Screenshot enclosed to that post for the sake of clarity.

I've tried with and without the Core Option PE2 fix turned on or off. Same outcome. I tried also to apply a patch to my ISO as this game was heavily copy-protected but same result as well...

I'm using a RP2, latest Retropie version (3.7 final), this core freshly built (but same behavior with the other rearmed core). Core options all by default/auto. No video enhancement turned on or something. I'm using bios SCPH1001.BIN but it makes no difference as same behavior occurs with any other bios'. Maybe it's worth mentioning too that I tried with both regular cue/bin, ccd/img images as well as a compressed pbp. Same result each time :(

One fix is for me to go to hell with my french and plays the UK/US versions :) That's for sure but first french is nice and then maybe this issue could be somewhat related to the one @barbudreadmon is talking about here ( #53 ). Again thanks a lot for the hard work and if I can do anything to help give me a shout I'll be happy to assist. 

![c64bff20-5037-11e5-83b6-5dde1a4543e2](https://cloud.githubusercontent.com/assets/8100500/15267463/451a5374-19c3-11e6-9f6e-767674ef9a89.png)

**Comment by netux79** [comment]
This game doesn't work in any platform with any version. The fix used to work in the original PCSX but not here. It requires someone with PSX knowledge to get into the code and fix this but from the design this game has trouble on PCSX because of some timing issues.

Question: Are you sure you can play the game with PCSX Rearmed passing the shooting gallery section? Please confirm :) Otherwise I think you will need a different emulator.

**Comment by blackman91** [comment]
Using Retroarch latest nightly on Android, the game always freezes in the shooting gallery even with the fix option enabled, any way this can be fixed now?

**Comment by Darknior** [comment]
Same problem for me. All 100% like Nemo93. So bad this game is excellent.

**Comment by SumavisionQ5** [comment]
A Chinese coder has forced setting the timing option on, and the problem has been solved. Unfortunatly, he does not release the modified codes. Hope this information can help someone here with enough knowledge fix it.

**Comment by blackman91** [comment]
Who is this Chinese coder? Link to the supposed fix?

**Comment by nemo93** [comment]
Now this core supports chd I went on recompressing my library and gave a new try to PE2, French version. I've updated Retroarch, this core and did apply no patch whatsoever on the "iso". I also get the "sbi" files associated to each disk and... it works! I can get pass the screen described above. I still don't know if I could get pass the shooting range but for sure it's better!

**Comment by AnotherLife** [comment]
In other regions if you set PSX clock to 70 you can pass the shooting range.
